some minor changes in config files

diff --git a/bin/nwr b/bin/nwr
--- a/bin/nwr
+++ b/bin/nwr
@@ -21,78 +21,90 @@
 
 set -o nounset                              # Treat unset variables as an error
 
-E_XCD=86							# Can't change directory?
+E_XCD=86                                    # Can't change directory?
 DIR="/home/jakub/skola/01_phd/02_dissertation/thesis"
 LOGFILE="nwords.txt"
 cd "$DIR"
 WRITE_DIFF="false"
 EDIT="false"
+NWORDS="/tmp/NWORDS"
+TEMPOLD="/tmp/TEMPOLD"
+TEMPNEW="/tmp/TEMPNEW"
 
 # Doublecheck if in the right directory
-if [ "$(pwd)" != "$DIR" ]		# Not in ~/skola/01_phd/02_dissertation/thesis?
+if [ "$(pwd)" != "$DIR" ]                 # Not in ~/skola/01_phd/02_dissertation/thesis?
 then
-  echo "Can't change to $DIR."
-  exit $E_XCD
+    echo "Can't change to $DIR."
+    exit $E_XCD
 fi
 
 while getopts "hwe" OPTION; do
-        case $OPTION in
+    case $OPTION in
 
-				e)
-						EDIT="true"
-						;;
+        e)
+            EDIT="true"
+            ;;
 
-                w)
-                        WRITE_DIFF="true"
-                        ;;
+        w)
+            WRITE_DIFF="true"
+            ;;
 
-                h)
-                        echo "Usage:"
-						echo "  nwr        Print the diff of the log file and the current state of the tex files"
-						echo "  nwr -e     Edit the log file manually"
-						echo "  nwr -h     Print help (this output)"
-                        echo "  nwr -w     Write the differences to the log file"
-                        exit 0
-                        ;;
+        h)
+            echo "Usage:"
+            echo "  nwr        Print the diff of the log file and the current state of the tex files"
+            echo "  nwr -e     Edit the log file manually"
+            echo "  nwr -h     Print help (this output)"
+            echo "  nwr -w     Write the differences to the log file"
+            exit 0
+            ;;
 
-        esac
+    esac
 done
 
 if [[ $EDIT = "true" ]]; then
-	vim $LOGFILE
-	exit
+    vim $LOGFILE
+    exit
 fi
 
 
 # check if the wc command is available
 if command -v wc >/dev/null 2>&1
 then
-	FILELIST=$(find . -type f -iname "*tex" | sort -d)
-	# the temporary count of words
-	wc -w $FILELIST > /tmp/NWORDS
+    FILELIST=$(find . -type f -iname "*tex" | sort -d)
+    # the temporary count of words
+    wc -w $FILELIST > $NWORDS
 
-	tail --lines=8 $LOGFILE > /tmp/TEMPOLD
-	tail --lines=8 /tmp/NWORDS > /tmp/TEMPNEW
+    tail --lines=8 $LOGFILE > $TEMPOLD
+    tail --lines=8 $NWORDS > $TEMPNEW
 
-	diff /tmp/TEMPOLD /tmp/TEMPNEW > /dev/null
-	comp_value=$?
-	if [ $comp_value -eq 1 ]
-	then
-		echo "Some .tex files have been changed:"
-		diff -s /tmp/TEMPOLD /tmp/TEMPNEW
-		# if the -t option hasn't been passed write wc to file
-		if [[ $WRITE_DIFF = "true" ]]
-		then
-			echo "" >> $LOGFILE
-			date >> $LOGFILE
-			cat /tmp/NWORDS >> $LOGFILE
-		fi
-	else
-		echo "No changes in .tex files."
-	fi
+    diff $TEMPOLD $TEMPNEW > /dev/null
+    comp_value=$?
+    if [[ $comp_value -eq 1 ]]
+    then
+        echo "Some .tex files have been changed:"
+        diff -s $TEMPOLD $TEMPNEW
+        # if the -w option has been passed write wc to file
+        if [[ $WRITE_DIFF = "true" ]]
+        then
+            echo "" >> $LOGFILE
+            date >> $LOGFILE
+            cat $NWORDS >> $LOGFILE
+            echo ""
+            echo "Changes written to ./$LOGFILE."
+        fi
+		TO=$(tail --lines=1 $TEMPOLD | tr -d [:alpha:][:blank:])
+		TN=$(tail --lines=1 $TEMPNEW | tr -d [:alpha:][:blank:])
+		let DIFFERENCE=TN-TO
+		echo ""
+		echo "Total difference: $DIFFERENCE words"
+    else
+        echo "No changes in .tex files:"
+        echo ""
+        cat $TEMPOLD
+    fi
 else
-	echo "I require \"wc\" but it's not installed.  Aborting."
-	exit 1
+    echo "I require \"wc\" but it's not installed.  Aborting."
+    exit 1
 fi
 
 exit
