feat(wt): add function to handle dirtry worktree

diff --git a/local/bin/wt b/local/bin/wt
--- a/local/bin/wt
+++ b/local/bin/wt
@@ -16,11 +16,28 @@ post_add () {
   fi
 }
 
+handle_dirty_worktree() {
+  path=$1
+  echo -e "fatal: '$path' contains modified or untracked files\n"
+  cd "$path" && git status || echo "Cannot cd to $path" && exit
+  echo -e "" &&  if [[ $(git status -s) =~ " M" ]]; then git diff; else git diff --cached; fi
+  echo -e "\nUse 'wt rm f' to delete the worktree"
+}
+
 if [[ $# -eq 0 ]]; then
   git worktree list
   exit
 elif [[ $# -eq 1 ]]; then
   command=$1
+  force=0
+elif [[ $# -eq 2 ]]; then
+  command=$1
+  if [[ $command == "rm" ]] && [[ $2 == "f" ]]; then
+    force=1
+  else
+    echo "Bad argument \"$2\" for command \"rm\". Acceptable values: \"f\"."
+    exit
+  fi
 else
   echo "Too many arguments."
   exit
@@ -40,7 +57,11 @@ if [[ $command == "rm" ]]; then
     echo "No worktree selected."
     exit
   fi
-  git worktree remove "$selected" && echo "Removed worktree at $selected"
+  if [[ $force -eq 1 ]]; then
+    git worktree remove --force "$selected" && echo "Force-removed worktree at $selected"
+  else
+    git worktree remove "$selected" 2>/dev/null && echo "Removed worktree at $selected" || handle_dirty_worktree $selected
+  fi
 elif [[ $command == "add" ]]; then
   existing_worktrees=$(ls "$toplevel/.." | grep -- "^feat-[0-9]")
   available_worktrees=$(comm -23 <(echo "$feature_worktrees" | tr " " "\n") <(echo "$existing_worktrees"))
